import type { FastifyInstance } from 'fastify'; import { z } from 'zod'; import { AppError } from '../../../errors/app-error.js'; import { queueNames } from '../../../infrastructure/queue-registry.js'; import { requireAdmin } from '../../admin/auth/require-admin.js'; import { AutomationSettingsService,automationSettingsSchema } from '../automation-settings.service.js'; import { FollowUpService } from '../follow-up.service.js';
const template=z.object({name:z.string().trim().min(1).max(100),trigger:z.enum(['ORDER_CONFIRMATION_REMINDER','ABANDONED_ORDER','CUSTOMER_REQUESTED_FOLLOWUP','POST_ORDER','REVIEW_REQUEST','REORDER']),delayMinutes:z.number().int().min(0).max(43200),message:z.string().trim().min(1).max(2000),enabled:z.boolean()}).strict();
const manual=z.object({customerId:z.uuid(),conversationId:z.uuid(),orderId:z.uuid().optional(),scheduledAt:z.iso.datetime(),message:z.string().trim().min(1).max(2000)}).strict();
export async function automationRoutes(app:FastifyInstance){const db=app.prisma as any;const settings=new AutomationSettingsService(app.prisma);const service=new FollowUpService(app.prisma,app.queues[queueNames.customerFollowups] as any);const guard={preHandler:requireAdmin};
 app.get('/api/admin/settings/automation',guard,async()=>({success:true,data:await settings.get()}));app.put('/api/admin/settings/automation',guard,async req=>{const p=automationSettingsSchema.safeParse(req.body);if(!p.success)throw new AppError('Invalid automation settings',400,'VALIDATION_ERROR');return{success:true,data:await settings.update(p.data)}});
 app.get('/api/admin/automation/templates',guard,async()=>({success:true,data:await db.followUpTemplate.findMany({orderBy:{name:'asc'}})}));app.put('/api/admin/automation/templates',guard,async req=>{const p=template.safeParse(req.body);if(!p.success)throw new AppError('Invalid follow-up template',400,'VALIDATION_ERROR');return{success:true,data:await db.followUpTemplate.upsert({where:{trigger:p.data.trigger},create:p.data,update:p.data})}});
 app.get('/api/admin/automation/stats',guard,async()=>{const start=new Date();start.setHours(0,0,0,0);const [pending,sent,cancelled,failed,abandoned]=await Promise.all([db.followUp.count({where:{status:'PENDING'}}),db.followUp.count({where:{status:'SENT',sentAt:{gte:start}}}),db.followUp.count({where:{status:'CANCELLED'}}),db.followUp.count({where:{status:{in:['FAILED','BLOCKED','NOT_ELIGIBLE']}}}),db.order.count({where:{status:'ABANDONED'}})]);return{success:true,data:{pending,sentToday:sent,cancelled,failed,abandonedOrders:abandoned}}});
 app.get('/api/admin/automation/followups',guard,async req=>{const q=req.query as any;const page=Math.max(1,Number(q.page)||1),limit=Math.min(100,Math.max(1,Number(q.limit)||25));const allowed=['PENDING','SENT','CANCELLED','FAILED','BLOCKED','NOT_ELIGIBLE'];const where=allowed.includes(q.status)?{status:q.status}:{};const [items,total]=await Promise.all([db.followUp.findMany({where,include:{customer:{select:{id:true,name:true,platform:true}},conversation:{select:{id:true,status:true,channel:true}},order:{select:{id:true,status:true}}},orderBy:{createdAt:'desc'},skip:(page-1)*limit,take:limit}),db.followUp.count({where})]);return{success:true,data:{items,total,page,limit}}});
 app.post('/api/admin/automation/followups',guard,async req=>{const p=manual.safeParse(req.body);if(!p.success)throw new AppError('Invalid follow-up schedule',400,'VALIDATION_ERROR');return{success:true,data:await service.schedule({...p.data,type:'CUSTOMER_REQUESTED_FOLLOWUP',scheduledAt:new Date(p.data.scheduledAt),createdBy:'admin'})}});
 app.post<{Params:{id:string}}>('/api/admin/automation/followups/:id/cancel',guard,async req=>({success:true,cancelled:await service.cancel(req.params.id)}));app.post<{Params:{id:string}}>('/api/admin/automation/followups/:id/retry',guard,async req=>{await service.retry(req.params.id);return{success:true}});
 app.get('/api/admin/automation/abandoned-orders',guard,async req=>{const q=req.query as any;const page=Math.max(1,Number(q.page)||1),limit=Math.min(100,Math.max(1,Number(q.limit)||25));const where={status:'ABANDONED'};const [items,total]=await Promise.all([db.order.findMany({where,include:{customer:true,conversation:true,items:true,followUps:{orderBy:{createdAt:'desc'},take:1}},orderBy:{updatedAt:'desc'},skip:(page-1)*limit,take:limit}),db.order.count({where})]);return{success:true,data:{items,total,page,limit}}});
}
