import type { PrismaClient } from '@alzeena/database';
import type { FollowUpDeliveryProvider } from './follow-up-delivery.js';
import { AutomationSettingsService } from './automation-settings.service.js';
import { enqueueFollowUp } from './follow-up.queue.js';

// Meta standard messaging permits proactive UPDATE messages only within 24 hours.
// Legacy order-status message tags stopped being accepted on 2026-04-27, so this engine fails closed without a verified opt-in token.
const META_STANDARD_WINDOW_MS=24*60*60*1000;
type FollowType='ORDER_CONFIRMATION_REMINDER'|'ABANDONED_ORDER'|'CUSTOMER_REQUESTED_FOLLOWUP'|'POST_ORDER'|'REVIEW_REQUEST'|'REORDER';
type QueueLike=Parameters<typeof enqueueFollowUp>[0];
export class FollowUpService {
 private db:any; private settings:AutomationSettingsService;
 constructor(prisma:PrismaClient,private queue:QueueLike,private delivery?:FollowUpDeliveryProvider,private orderLifecycle?:{markOrderAbandoned(id:string):Promise<unknown>}){this.db=prisma as any;this.settings=new AutomationSettingsService(prisma);}
 async schedule(input:{customerId:string;conversationId:string;orderId?:string;type:FollowType;scheduledAt:Date;message:string;createdBy?:string}){
  const config=await this.settings.get(); if(!config.enabled) throw new Error('AUTOMATION_DISABLED');
  const [customer,conversation,count,last]=await Promise.all([this.db.customer.findUnique({where:{id:input.customerId}}),this.db.conversation.findUnique({where:{id:input.conversationId}}),this.db.followUp.count({where:{conversationId:input.conversationId,status:{in:['PENDING','PROCESSING','SENT']}}}),this.db.followUp.findFirst({where:{conversationId:input.conversationId,status:'SENT'},orderBy:{sentAt:'desc'}})]);
  if(!customer||!conversation)throw new Error('AUTOMATION_CONTEXT_NOT_FOUND'); if(customer.automationOptOut)throw new Error('CUSTOMER_OPTED_OUT'); if(config.humanHandoverBlock&&conversation.status==='HUMAN')throw new Error('HUMAN_HANDOVER_BLOCK'); if(conversation.status==='CLOSED')throw new Error('CONVERSATION_CLOSED'); if(count>=config.maximumFollowUpsPerConversation)throw new Error('FOLLOWUP_LIMIT_REACHED'); if(last?.sentAt&&input.scheduledAt.getTime()-last.sentAt.getTime()<config.minimumFollowUpIntervalMinutes*60000)throw new Error('FOLLOWUP_INTERVAL');
  const slot=input.scheduledAt.toISOString().slice(0,16); const idempotencyKey=`${input.customerId}:${input.conversationId}:${input.type}:${slot}`;
  const existing=await this.db.followUp.findUnique({where:{idempotencyKey}}); if(existing){if(existing.status==='PENDING')await enqueueFollowUp(this.queue,existing.id,existing.scheduledAt);return existing;}
  if(conversation.channel==='MESSENGER'&&input.scheduledAt.getTime()>Date.now()+META_STANDARD_WINDOW_MS){const blocked=await this.db.followUp.create({data:{customerId:input.customerId,conversationId:input.conversationId,orderId:input.orderId,type:input.type,scheduledAt:input.scheduledAt,idempotencyKey,status:'NOT_ELIGIBLE',failureReason:'Outside Meta 24-hour window; no verified notification opt-in',payload:{message:input.message.slice(0,2000),createdBy:input.createdBy??'system'}}});await this.log('FOLLOWUP_FAILED',blocked.id,{status:'NOT_ELIGIBLE',reason:blocked.failureReason});return blocked;}
  const follow=await this.db.followUp.create({data:{customerId:input.customerId,conversationId:input.conversationId,orderId:input.orderId,type:input.type,scheduledAt:input.scheduledAt,idempotencyKey,payload:{message:input.message.slice(0,2000),createdBy:input.createdBy??'system'}}}); await enqueueFollowUp(this.queue,follow.id,input.scheduledAt);
  await this.log('FOLLOWUP_CREATED',follow.id,{type:input.type,scheduledAt:input.scheduledAt.toISOString()}); return follow;
 }
 async scheduleConfirmationReminder(input:{customerId:string;conversationId:string;orderId:string}){const config=await this.settings.get();const template=await this.db.followUpTemplate.findUnique({where:{trigger:'ORDER_CONFIRMATION_REMINDER'}});if(template&&!template.enabled)return null;return this.schedule({...input,type:'ORDER_CONFIRMATION_REMINDER',scheduledAt:new Date(Date.now()+(template?.delayMinutes??config.confirmationReminderDelayMinutes)*60000),message:template?.message??'ভাই, আপনার অর্ডারটা এখনও confirm করা হয়নি। নিতে চাইলে জানিয়ে দিন।'});}
 async cancelPending(conversationId:string,reason:string){const now=new Date();const changed=await this.db.followUp.updateMany({where:{conversationId,status:'PENDING'},data:{status:'CANCELLED',cancelledAt:now,failureReason:reason.slice(0,500)}});if(changed.count)await this.log('FOLLOWUP_CANCELLED',conversationId,{reason,count:changed.count});return changed.count;}
 async cancel(id:string,reason='admin_cancelled'){const f=await this.db.followUp.updateMany({where:{id,status:'PENDING'},data:{status:'CANCELLED',cancelledAt:new Date(),failureReason:reason}});if(f.count)await this.log('FOLLOWUP_CANCELLED',id,{reason});return f.count;}
 async retry(id:string){const f=await this.db.followUp.findUnique({where:{id}});if(!f||!['FAILED','BLOCKED','NOT_ELIGIBLE'].includes(f.status))throw new Error('FOLLOWUP_NOT_RETRYABLE');const scheduledAt=new Date(Date.now()+5000);await this.db.followUp.update({where:{id},data:{status:'PENDING',scheduledAt,failureReason:null}});await enqueueFollowUp(this.queue,id,scheduledAt);}
 async execute(id:string){const follow=await this.db.followUp.findUnique({where:{id},include:{customer:true,conversation:true,order:true}});if(!follow||!['PENDING','PROCESSING'].includes(follow.status))return {cancelled:true};const config=await this.settings.get();const emergency=await this.db.setting.findUnique({where:{key:'messenger.emergency_stop'}});const invalid=emergency?.value==='true'||!config.enabled||follow.customer.automationOptOut||follow.conversation.status==='HUMAN'||follow.conversation.status==='CLOSED'||(follow.order&&['SUBMITTED','COMPLETED','CANCELLED'].includes(follow.order.status));if(invalid){await this.cancel(id,'no_longer_relevant');return {cancelled:true};}
  await this.db.followUp.update({where:{id},data:{status:'PROCESSING',attempts:{increment:1}}});if(follow.conversation.channel!=='MESSENGER'||!follow.customer.platformUserId){await this.mark(id,'NOT_ELIGIBLE','Channel delivery is not implemented');return {blocked:true};}
  const lastUser=await this.db.message.findFirst({where:{conversationId:follow.conversationId,role:'USER'},orderBy:{createdAt:'desc'}});if(!lastUser||Date.now()-lastUser.createdAt.getTime()>META_STANDARD_WINDOW_MS){await this.mark(id,'NOT_ELIGIBLE','Outside Meta 24-hour messaging window; no verified opt-in token');return {blocked:true};}
  if(!this.delivery||this.delivery.channel!=='MESSENGER'){await this.mark(id,'BLOCKED','Messenger provider unavailable');return {blocked:true};}const message=String((follow.payload as any).message??'').slice(0,2000);const result=await this.delivery.deliver({recipientId:follow.customer.platformUserId,message});if(result.success){await this.db.followUp.update({where:{id},data:{status:'SENT',sentAt:new Date(),failureReason:null}});await this.log('FOLLOWUP_SENT',id,{provider:'messenger'});return {sent:true};}if(result.retryable){await this.db.followUp.update({where:{id},data:{status:'PENDING',failureReason:result.errorCode}});throw new Error('TEMPORARY_FOLLOWUP_DELIVERY_FAILURE');}await this.mark(id,'FAILED',result.errorCode??'delivery_failed');return {sent:false}; }
 async detectAbandoned(){const config=await this.settings.get();const template=await this.db.followUpTemplate.findUnique({where:{trigger:'ABANDONED_ORDER'}});const cutoff=new Date(Date.now()-(template?.delayMinutes??config.abandonedOrderDelayMinutes)*60000);const orders=await this.db.order.findMany({where:{status:{in:['DRAFT','AWAITING_INFORMATION','AWAITING_CONFIRMATION']},updatedAt:{lte:cutoff},conversation:{is:{lastMessageAt:{lte:cutoff}}}},include:{conversation:true},take:100});for(const o of orders){await this.db.followUp.updateMany({where:{orderId:o.id,status:'PENDING'},data:{status:'CANCELLED',cancelledAt:new Date(),failureReason:'replaced_by_abandoned_order'}});if(!this.orderLifecycle)throw new Error('ORDER_LIFECYCLE_UNAVAILABLE');await this.orderLifecycle.markOrderAbandoned(o.id);await this.log('ABANDONED_ORDER_DETECTED',o.id,{customerId:o.customerId});if(template?.enabled===false)continue;try{await this.schedule({customerId:o.customerId,conversationId:o.conversationId,orderId:o.id,type:'ABANDONED_ORDER',scheduledAt:new Date(),message:template?.message??'ভাই, আপনার অর্ডারটি সম্পূর্ণ হয়নি। নিতে চাইলে জানিয়ে দিন।'});}catch{/* policy/settings can intentionally suppress */}}return orders.length;}
 async failAfterRetries(id:string,reason:string){await this.mark(id,'FAILED',reason);}
 private async mark(id:string,status:'FAILED'|'BLOCKED'|'NOT_ELIGIBLE',reason:string){await this.db.followUp.update({where:{id},data:{status,failureReason:reason.slice(0,500)}});await this.log('FOLLOWUP_FAILED',id,{status,reason});}
 private log(type:string,reference:string,metadata:Record<string,unknown>){return this.db.systemLog.create({data:{level:type==='FOLLOWUP_FAILED'?'ERROR':'INFO',type,event:type,module:'automation',message:type.replaceAll('_',' ').toLowerCase(),metadata:{reference,...metadata,timestamp:new Date().toISOString()}}});}
}
