'use client';
import { useCallback,useEffect,useState } from 'react';
import { AdminAccess } from '../_components/admin-access';
import { OperationsNav } from '../_components/operations-nav';
import { Badge,ErrorState,LoadingRows } from '../_components/ui';
import { adminRequest,useAdminPassword } from '../_lib/admin-client';
type Component={name:string;status:string;checkedAt:string;latencyMs:number|null;lastError:{message:string;at:string}|null};
type Health={status:string;components:Component[];workers:{name:string;heartbeat:string|null}[];checkedInMs:number;timestamp:string};
export default function SystemHealth(){const {password,setPassword,hydrated}=useAdminPassword();const [data,setData]=useState<Health>();const [error,setError]=useState('');const [loading,setLoading]=useState(false);
const load=useCallback(async()=>{if(!password)return;setLoading(true);setError('');try{setData((await adminRequest<{data:Health}>('/admin/system/health',password)).data)}catch(e){setError(e instanceof Error?e.message:'Health check failed')}finally{setLoading(false)}},[password]);
useEffect(()=>{if(!hydrated||!password)return;void load();const timer=window.setInterval(()=>void load(),30_000);return()=>window.clearInterval(timer);},[hydrated,password,load]);
return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-8"><h1 className="text-3xl font-semibold">System Health</h1><p className="mt-1 text-stone-600">Bounded checks use local state, database, Redis, worker heartbeats and circuit state—no external request is made on refresh.</p><OperationsNav active="/admin/system-health"/><div className="mt-5"><AdminAccess password={password} onPasswordChange={setPassword} onLoad={()=>void load()} loading={loading}/></div>{error&&<div className="mt-5"><ErrorState message={error} retry={()=>void load()}/></div>}{loading&&!data?<LoadingRows/>:data&&<><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{data.components.map(c=><article key={c.name} className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold">{c.name}</h2><Badge tone={/up|ready|closed/i.test(c.status)?'green':/unknown|degraded|open/i.test(c.status)?'amber':'red'}>{c.status}</Badge></div><p className="mt-3 text-xs text-stone-500">Checked {new Date(c.checkedAt).toLocaleString()}{c.latencyMs!==null?` · ${c.latencyMs} ms`:''}</p>{c.lastError&&<p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-800">{c.lastError.message}<br/><span className="text-xs">{new Date(c.lastError.at).toLocaleString()}</span></p>}</article>)}</div><p className="mt-4 text-xs text-stone-500">Snapshot completed in {data.checkedInMs} ms. Auto-refresh is consolidated every 30 seconds.</p></>}</main>}
